name: alphanet-bench-erc20

on:
  workflow_dispatch:
    inputs:
      jmeterJmx:
        type: choice
        description: Make a choice of jmx
        required: true
        options:
        - alphanet-bench-erc20.jmx
        - alphanet-bench-logRequest.jmx
        - alphanet-bench-swap.jmx
        - testnet-bench-erc20.jmx
        - testnet-bench-swap.jmx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  
      - name: Build with Maven
        run:
          mvn clean package --file pom.xml
      - name: Install Dependencies
        run: 
          pip install Web3
      - name: Start  Monit Block Message
        run: 
          python utils/retrieve_block.py & 
      - name: jmeter run
        run:
          mvn jmeter:jmeter@configuration2 -DjmeterTest=${{ github.event.inputs.jmeterJmx }}
      - name: collect block message
        run: |
          cat block.csv
          cp block.csv target/jmeter
      - name: Publish reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jfoa-build-reports-${{ runner.os }}
          path: target/jmeter
